[package]
name = "playdate-rs"
description = "Safe Rust bindings for the Playdate SDK C-CPI"
repository = "https://github.com/rusty-crank/playdate-rs"
categories = ["api-bindings", "embedded", "game-development", "no-std"]
documentation = "https://docs.rs/playdate-rs"
homepage = "https://github.com/rusty-crank/playdate-rs"
keywords = ["playdate", "gamedev"]
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = { version = "0.2", default-features = false, features = ["libm"] }
playdate-rs-sys = { workspace = true }
playdate-rs-macros = { workspace = true }
spin = "0.10.0"
no_std_io = { version = "0.6.0", features = ["alloc"] }
bitmask-enum = "2.2.5"
rand = { version = "0.9.1", features = ["small_rng"], default-features = false }
futures-task = { version = "0.3.31", features = [
    "alloc",
], default-features = false }
url = { version = "2.5.4", default-features = false }
serde = { version = "1.0", default-features = false, features = [
    "alloc",
    "derive",
] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
base64 = { version = "0.22.1", default-features = false, features = ["alloc"] }

[[example]]
name = "hello_world"
crate-type = ["cdylib", "staticlib"]

[[example]]
name = "mandelbrot"
crate-type = ["cdylib", "staticlib"]

[[example]]
name = "http"
crate-type = ["cdylib", "staticlib"]

[[example]]
name = "menu"
crate-type = ["cdylib", "staticlib"]

[[example]]
name = "timer"
crate-type = ["cdylib", "staticlib"]

[[example]]
name = "websocket"
crate-type = ["cdylib", "staticlib"]

[[example]]
name = "chatgpt"
crate-type = ["cdylib", "staticlib"]
