[package]
name = "playdate-rs"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "Rust type-safe bindings for the Playdate SDK"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
playdate-rs-sys = { version = "0.0.1", path = "../playdate-rs-sys" }
spin = "0.9.8"
