[workspace]
resolver = "2"
members = [
    "examples/hello-world",
    "examples/mandelbrot",
    "playdate-rs",
    "playdate-rs/macros",
    "playdate-rs-cli",
    "playdate-rs-sys",
]

[workspace.package]
version = "0.0.1"
edition = "2021"
authors = ["Wenyu Zhao <wenyu.zhao@anu.edu.au>"]
license = "MIT"
