[alias]
playdate = "run --package playdate-cli --"
playdate-gen-arm-binding = "run --bin gen-thumbv7em-binding --features generate -- /usr/local/playdate/gcc-arm-none-eabi-9-2019-q4-major/lib/gcc/arm-none-eabi/9.2.1"
