[package]
name = "playdate-cli"
description = "The CLI tools for playdate-rs"
repository = "https://github.com/rusty-crank/playdate-rs"
categories = [
    "api-bindings",
    "command-line-utilities",
    "embedded",
    "game-development",
    "no-std",
]
homepage = "https://github.com/rusty-crank/playdate-rs"
keywords = ["playdate", "gamedev"]
version = "0.0.15"
edition.workspace = true
authors.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "cargo-playdate"
path = "src/main.rs"

[[bin]]
name = "pd"
path = "src/bin/pd.rs"

[dependencies]
anyhow = { version = "1.0.98", features = ["backtrace"] }
cargo_metadata = "0.19.2"
clap = { version = "4.5.37", features = ["derive"] }
clap-cargo = "0.15.2"
env_logger = "0.11.8"
log = "0.4.27"
minijinja = "2.9.0"
home = "0.5.11"
toml = "0.8.22"
