name: Cargo Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Install Ubuntu Packages
        run: |
          sudo apt update
          sudo apt install -y libwebkit2gtk-4.0-dev gcc-arm-none-eabi
      - name: Install Playdate SDK
        run: |
          curl -L https://download-keycdn.panic.com/playdate_sdk/Linux/PlaydateSDK-2.0.3.tar.gz | tar xz
          export PLAYDATE_SDK_PATH=$(pwd)/PlaydateSDK-2.0.3
      - uses: actions/checkout@v3
      - run: rustup update stable && rustup default stable && cargo target add thumbv7em-none-eabihf
      - run: cargo build --workspace
      - run: cargo build --workspace --release
      - run: cargo build --workspace --exclude playdate-cli --target thumbv7em-none-eabihf
      - run: cargo build --workspace --exclude playdate-cli --target thumbv7em-none-eabihf --release
      - run: cargo test -p playdate-rs-sys
      - run: cargo test -p playdate-rs-sys --release
      - run: cargo fmt -- --check
      - run: cargo clippy -D warnings
