name: Cargo Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  PLAYDATE_SDK_VERSION: 2.0.3
  PLAYDATE_SDK_PATH: ${{ github.workspace }}/PlaydateSDK

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - thumbv7em-none-eabihf
        profile:
          - debug
          - release
    env:
      PROFILE_FLAG: ${{ matrix.profile == 'release' && '--release' || '' }}
    steps:
      - name: Install Ubuntu Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev gcc-arm-none-eabi
      - name: Install Playdate SDK
        run: |
          mkdir PlaydateSDK
          curl -L https://download-keycdn.panic.com/playdate_sdk/Linux/PlaydateSDK-${{ env.PLAYDATE_SDK_VERSION }}.tar.gz | tar xz --strip 1 -C PlaydateSDK
          ls PlaydateSDK
          echo ${PLAYDATE_SDK_PATH}
          ls ${PLAYDATE_SDK_PATH}
          echo ---
          ls ${PLAYDATE_SDK_PATH}/bin
          echo ---
          file ${PLAYDATE_SDK_PATH}/bin/pdc
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Rust Toolchain
        run: rustup update stable && rustup target add ${{ matrix.target }}
      - name: Cargo Build (${{ matrix.target }}, ${{ matrix.profile }})
        run: |
          echo ${PLAYDATE_SDK_PATH}
          ls ${PLAYDATE_SDK_PATH}
          echo ---
          ls ${PLAYDATE_SDK_PATH}/bin
          echo ---
          file ${PLAYDATE_SDK_PATH}/bin/pdc
          cargo build --workspace --target ${{ matrix.target }} ${{ env.PROFILE_FLAG }} --exclude playdate-cli
      - name: Cargo Test (${{ matrix.target }}, ${{ matrix.profile }})
        run: cargo test -p playdate-rs-sys --target ${{ matrix.target }} ${{ env.PROFILE_FLAG }}
        if: ${{ matrix.target == 'x86_64-unknown-linux-gnu' }}
      - name: Cargo clippy checks
        run: cargo clippy --target ${{ matrix.target }} ${{ env.PROFILE_FLAG }} -- -D warnings

  format-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Rust Toolchain
        run: rustup update stable
      - name: Cargo fmt checks
        run: cargo fmt -- --check
