name: Checks

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  PLAYDATE_SDK_VERSION: 2.0.3
  PLAYDATE_SDK_PATH: ${{ github.workspace }}/PlaydateSDK

jobs:
  # Cargo package checks
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64
          - thumbv7em
        profile:
          - debug
          - release
    env:
      CARGO_BUILD_FLAGS: --target ${{ matrix.target == 'x86_64' && 'x86_64-unknown-linux-gnu' || 'thumbv7em-none-eabihf' }} ${{ matrix.profile == 'release' && '--release' || '' }}
      CARGO_TARGET: ${{ matrix.target == 'x86_64' && 'x86_64-unknown-linux-gnu' || 'thumbv7em-none-eabihf' }}
    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v3
      # Install Playdate SDK
      - name: Install Playdate SDK
        run: |
          mkdir PlaydateSDK
          curl -L https://download-keycdn.panic.com/playdate_sdk/Linux/PlaydateSDK-${{ env.PLAYDATE_SDK_VERSION }}.tar.gz | tar xz --strip 1 -C PlaydateSDK
      # Setup up rust toolchain
      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: ${{ env.CARGO_TARGET }}
          components: clippy, rust-src
      # Build all projects except playdate-cli
      - name: Cargo Build (${{ matrix.target }}, ${{ matrix.profile }})
        run: cargo build --workspace ${{ env.CARGO_BUILD_FLAGS }} --exclude playdate-cli
      # Test sys package
      - name: Cargo Test (${{ matrix.target }}, ${{ matrix.profile }})
        run: cargo test -p playdate-rs-sys ${{ env.CARGO_BUILD_FLAGS }}
        if: ${{ matrix.target == 'x86_64' }}
      # Format checks
      - name: Cargo clippy checks
        run: cargo clippy ${{ env.CARGO_BUILD_FLAGS }} -- -D warnings
        if: ${{ matrix.target == 'x86_64' }}

  build-examples:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64
          - thumbv7em
        example:
          - hello_world
          - mandelbrot
    env:
      CARGO_PROFILE_BUILD_FLAGS: -p playdate-rs ${{ matrix.target == 'thumbv7em' && '--device' || '' }}
      CARGO_TARGET: ${{ matrix.target == 'x86_64' && 'x86_64-unknown-linux-gnu' || 'thumbv7em-none-eabihf' }}
    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v3
      # Install Playdate SDK
      - name: Install Playdate SDK
        run: |
          mkdir PlaydateSDK
          curl -L https://download-keycdn.panic.com/playdate_sdk/Linux/PlaydateSDK-${{ env.PLAYDATE_SDK_VERSION }}.tar.gz | tar xz --strip 1 -C PlaydateSDK
      # Setup up rust toolchain
      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: ${{ env.CARGO_TARGET }}
          components: rust-src
      # Build examples
      - name: Build playdate-rs example (${{ matrix.example }})
        run: cargo playdate build --example ${{ matrix.example }} ${{ env.CARGO_PROFILE_BUILD_FLAGS }}

  # Cargo format checks
  format-checks:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v3
      # Setup up rust toolchain
      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      # Format checks
      - name: Cargo fmt checks
        run: cargo fmt -- --check

  # Playdate CLI integration checks
  cli-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64
          - thumbv7em
        profile:
          - debug
          - release
        playdate-rs-version:
          - head
          - crates-io
    env:
      CARGO_PROFILE_BUILD_FLAGS: ${{ matrix.target == 'thumbv7em' && '--device' || '' }} ${{ matrix.profile == 'release' && '--release' || '' }}
      CARGO_TARGET: ${{ matrix.target == 'x86_64' && 'x86_64-unknown-linux-gnu' || 'thumbv7em-none-eabihf' }}
    steps:
      # Install packages
      - name: Install gcc-arm-none-eabi
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi
        if: ${{ matrix.target == 'thumbv7em' }}
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v3
      # Install Playdate SDK
      - name: Install Playdate SDK
        run: |
          mkdir PlaydateSDK
          curl -L https://download-keycdn.panic.com/playdate_sdk/Linux/PlaydateSDK-${{ env.PLAYDATE_SDK_VERSION }}.tar.gz | tar xz --strip 1 -C PlaydateSDK
      # Setup up rust toolchain
      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: ${{ env.CARGO_TARGET }}
          components: clippy, rust-src, rustfmt
      # Install playdate-cli
      - name: Install playdate-cli
        run: |
          cargo install --path .
          rm -r ../.cargo
        working-directory: playdate-cli
      # Init new project
      - name: Init cargo playdate project (crates.io)
        run: mkdir new-project && cd new-project && cargo playdate init
        if: ${{ matrix.playdate-rs-version == 'crates-io' }}
      - name: Init cargo playdate project (head)
        run: mkdir new-project && cd new-project && cargo playdate init --use-local-playdate-rs ${{ github.workspace }}/playdate-rs
        if: ${{ matrix.playdate-rs-version == 'head' }}
      # Build project
      - name: Build cargo playdate project
        run: cargo playdate build ${{ env.CARGO_PROFILE_BUILD_FLAGS }}
        working-directory: new-project
      # Format checks
      - name: Cargo fmt checks
        run: cargo fmt -- --check
        working-directory: new-project
      - name: Cargo clippy checks
        run: cargo clippy -- -D warnings
        working-directory: new-project
        if: ${{ matrix.target == 'x86_64' }}

  # Cargo format checks
  build-docs:
    runs-on: ubuntu-latest
    env:
      DOCS_RS: "1"
    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v3
      # Setup up rust toolchain
      - name: Setup Rust Toolchain
        run: rustup default nightly
      # Build docs
      - name: Build cargo docs (debug)
        run: cargo doc --workspace --no-deps
      - name: Build cargo docs (release)
        run: cargo doc --workspace --no-deps --release

  # Publish packages
  publish-crates:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [checks, format-checks, cli-checks, build-docs]
    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v3
      # Install Playdate SDK
      - name: Install Playdate SDK
        run: |
          mkdir PlaydateSDK
          curl -L https://download-keycdn.panic.com/playdate_sdk/Linux/PlaydateSDK-${{ env.PLAYDATE_SDK_VERSION }}.tar.gz | tar xz --strip 1 -C PlaydateSDK
      # Setup up rust toolchain
      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@nightly
      # Publish crates
      - name: Publish Crates
        uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          ignore-unpublished-changes: true
